\input texinfo @c - * - texinfo - * -
@c %**start of header
@setfilename zdl.info
@settitle ZigzagDownLoader (ZDL)
@c %**end of header

@documentencoding UTF-8
@documentlanguage en_US

@copying

 ZigzagDownLoader (ZDL)
 
 This program is free software: you can redistribute it and / or modify it
 under the terms of the GNU General Public License as published
 by the Free Software Foundation; either version 3 of the License,
 or (at your option) any later version.

 This program is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
 or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with this program. If not, see http://www.gnu.org/licenses/.
 
 Copyright @copyright{} 2011
 Gianluca Zoni <@email{zoninoz@@inventati.org}>

 For information or to collaborate on the project:
 @url{https://savannah.nongnu.org/projects/zdl}
 
 Gianluca Zoni (author)
 @url{http://inventati.org/zoninoz}
 @email{zoninoz@@inventati.org}

@end copying

@dircategory Network Applications
@direntry
* ZigzagDownLoader: (zdl). Download manager for Wget, Axel, cURL and RTMPDump. It has extensions for file hosting and video streaming services.
@end direntry

@ifinfo
@titlepage
@title ZigzagDownLoader manual (zdl)

@page
@vskip 0pt plus 1filll
@insertcopying
@end titlepage
@end ifinfo
@c @@@@@@@@@@@ MACROS @@@@@@@@@@@@@@@@@


@macro menuZdl
@ifhtml
@html
@end html
@end ifhtml
* Home:Top. ZigzagDownLoader@*
* The ZDL::@*Command synopsis, options and other arguments@*
* Streaming/hosting services::@*ZDL extensions and practical tips@*
* Installation and update::@*For GNU/Linux and Microsoft Windows/Cygwin@*
* Why this program::@*The sense of continuous ZIGZAG experimentation@*
@end macro

@macro menuUse
@ifhtml
@html
@end html
@end ifhtml
* Start ZDL::@*How to run the program and start downloads@*
* Stop ZDL::@*Program shutdown mode@*
* Check the downloads::@*How to control the processes started, queued or suspended@*
* User manuals::@*Documentation available for ZDL@*
@end macro

@macro menuTools
@ifhtml
@html
@end html
@end ifhtml
* Modes::@*Default, Lite, Interactive, Daemon@*
* Readline::@*The ZDL command line@*
* Editor::@*Integrated editor, to change the download queue@*
* Homonymy::@*Management of homonymous files and recovery of interrupted downloads@*
* IRC/XDCC::@*Downloading files via IRC-chat/XDCC commands@*
* Torrent::@*Downloading torrents with Aria2: URL magnet or torrent file@*
* Filters::@*Filters for extracting and selecting files and URLs@*
@end macro

@macro menuExt
@ifhtml
@html
@end html
@end ifhtml
* Create new extensions::@*Custom ZDL and new service Bash extensions@*
* Recommended software and dependencies::@*Useful programs for ZDL@*
* Conkeror::@*Command @command{zdl} for the browser@*
* zdl-xterm and XXXTerm/Xombrero::@*A script to connect ZDL to other programs@*
@end macro

@macro menuDev
@itemize
@item
@uref{https://joindiaspora.com/tags/zdl,,Updates in Diaspora*}
@item
@uref{https://savannah.nongnu.org/projects/zdl,,Sevannah/GNU development project}
@item
@uref{http://download-mirror.savannah.gnu.org/releases/zdl/,, Release packages of ZDL}
@item
@uref{http://git.savannah.gnu.org/cgit/zdl.git,,Repository Git (source version check)}
@end itemize
@end macro

@macro menuFooter
@ifhtml
@html
@end html
@end ifhtml
* Tags::Analytical indices@*

* Copying::Authors and License@*

* Contacts::For assistance or to participate
@end macro

@macro htmlstart
@ifhtml
@html
</p><a href="index.html">
<div class="header"></div>
</a>
<div class="container">
<div class="left">
<div class="nav">
<p style='color:#959595;text-align:right;font-weight:bold'>News <a href="https://savannah.nongnu.org/news/atom.php?group=zdl" target="_blank"><img src="https://savannah.nongnu.org/images/common/feed16.png" style="float:right;margin-left:5px"></a></p>
<!-- <iframe src="http://z0n1n0z.000webhostapp.com/zdl-feed2html.php" height="300px" width="100%" style="border-style:none;"></iframe> -->
<iframe src="http://zoninoz.altervista.org/zdl/zdl-feed2html.php" height="300px" width="100%" style="border-style:none;"></iframe>
</div><br>
@b{ZDL}
<div class="nav">
@menu
@menuZdl
@end menu
</div>
<br>
@b{How to use ZDL}
<div class="nav">
@menu
@menuUso
@end menu
</div>
<br>
@b{Tools and functions}
<div class="nav">
@menu
@menuTools
@end menu
</div>
<br>
@b{Expanding ZDL}
<div class="nav">
@menu
@menuExt
@end menu
</div>
</div>
<div class="content">
@end html
@end ifhtml
@end macro

@macro htmlend
@ifhtml
@html
<br>
</div>
<div class="footer">
<div class="contentfooter">
@menu
@menuFooter
@end menu
</div>
<div class="contentfooter">
@b {ZDL Project}
@menu
@menuDev
@end menu
</div>
</div>
</div>
@end html
@end ifhtml
@end macro

@c @@@@@@@@@@@@ end MACROS @@@@@@@@@@@@@@@@@@@@@@@@

@ifhtml
@node Top,The ZDL command, ,
@end ifhtml
@ifinfo
@node Top,The ZDL command, ,(dir)
@end ifinfo
@htmlstart
@top ZigzagDownLoader (ZDL)
@cindex why zdl

@c @man{3}

@c @ifman @unnumberedsec DESCRIPTION
@emph{ZigzagDownLoader} is a download manager:
@itemize @minus
@item
equipped with command line user interfaces (@emph{CLI}), for terminals (@emph{TUI}), graphics (@emph{GUI}) and for internet and web applications (@emph{Web-UI});
@item
handles downloads of some downloaders such as @emph{Aria2}, @emph{Axel}, @emph{Wget}, @emph{RTMPDump} or @emph{cURL}, using its potential (for example, download acceleration);
@item
extracts the URL of the files to be downloaded from file hosting and video streaming services;
@item
downloads @emph{TORRENT};
@item
automatically requests and downloads files via @emph{IRC/XDCC}, without any human interaction via chat;
@item
downloads movies @emph{LIVE} from some television networks
@item
extends web browsers, such as @emph{Conkeror}, @emph{XXXTerm/Xombrero} and, using @emph{Flashgot}), @emph{Firefox};
@item
the @emph{External Application Button} extension integrates ZDL into @emph{Firefox}, @emph{Chrome/Chromium} and @emph{Opera};
@item
using @emph{Cygwin}, it also works in @emph{Microsoft Windows} (CLI and TUI interfaces, also from @emph{Firefox} + @emph{Flashgot} of Windows).
@end itemize

The server and web interfaces, for remote and network control, make it a useful tool for a @emph{Network Attached Storage} (@emph{NAS}). The interfaces are @emph{responsive} and suitable for different devices. In particular, they can also be used as a remote control for launching multimedia files already downloaded or being downloaded, using a web browser on mobile devices.

Furthermore, the Web interfaces (@emph{Web-UI}) and graphics (@emph{GUI}) allow the quick and intuitive search and selection of @emph{files via XDCC}, without having to perform any IRC/chat.
All interfaces allow @emph{live-tv} recordings to be programmed.

But ZDL is also much more, because it can be:
@itemize @minus
@item
combined with other programs or inserted into a script, as a work tool
@item
extended by the user, who can develop new extensions suitable for their purposes
@item
a polyglot system, using different interpreters (for PHP, Javascript, Python, Perl, Awk ...) and Bash tools
@end itemize

ZigzagDownLoader is a "zigzag" program: it is not just a program, it is a laboratory and a system open to new inventions.

@c @end man

@unnumbered Free Software
ZDL is free software, released under the GPL (General Public License): @url{http://www.gnu.org/licenses/gpl.html}

@ref{Copying}.

@unnumbered Install ZDL
@ref{Installation and update}

@ifinfo
@menu
@emph{ZDL}
@menuZdl

@emph{How to use ZDL}
@menuUso

@emph{Tools and functions}
@menuTools

@emph{Expand ZDL}
@menuExt

@menuFooter
@end menu
@end ifinfo

@htmlend

@node The ZDL command, Streaming / hosting services, Top, Top

@htmlstart
@unnumbered The ZDL command
@cindex command zdl

ZDL is a Bash program, written mainly with the Bash language. Below is a summary of the synopsis, options and other arguments of the command @command{zdl}. For more information, consult the specialized sections. ZDL is prepared for the automatic completion of the arguments (use the @kbd{<Tab>} key).
@c @man{1}
@c @ifman @unnumberedsec NAME
@c @ifman @command{zdl} - CLI/TUI/GUI/Web-UI download manager for @emph{GNU/Linux} and @emph{Microsoft Windows + Cygwin}.

@c @ifman @unnumberedsec SYNOPSIS
@c @end man

@cindex synopsis
@unnumberedsec Synopsis

@c @man{2}
@command{zdl [@emph{OPTIONS}] [@emph{file} ...] [@emph{link} ...] [@emph{directory}]}
@c @end man

@cindex arguments
@unnumberedsec Arguments
@c @man{4}
@c @ifman @unnumberedsubsec Arguments
The order of options and other arguments is not important:

@table @emph
@item file
File names from which to extract the @emph{link}. The files must be text or DLC containers or TORRENT files, the latter marked by the extensions @emph{.dlc} and @emph{.torrent} respectively (ZDL processes the @emph{links} in memory in the @emph{directory} and those in input)

@item link
URL of files or web pages of hosting, streaming or redirection services (if omitted, ZDL processes those in memory in @emph{directory} and in @emph{files}). To download via @emph{IRC/XDCC}, the link must have the following form (port not necessary if it is 6667): @code{irc://[HOST[:PORT]]/[CHAN]/msg [PRIVMSG]}. ZDL also accepts links to @emph{xWeasel}, with protocol @code{xdcc://}.


@item directory
ZDL start directory and download destination (if omitted, it is the current one)

@end table
@c @end man
@cindex options
@unnumberedsubsec Options
@c @man{5}
@c @ifman @unnumberedsec OPTIONS
Short options not followed by values​can be contracted:
@option{-ufmd} is equivalent to @option{-u} @option{-f} @option{-m} @option{-d}

@table @option
@item -h, --help
@emph{ZigzagDownLoader (ZDL)} help

@item --list-extensions
@emph{ZigzagDownLoader (ZDL)} extensions list

@item --aria2
Download using @emph{Aria2}

@item --axel
Download using @emph{Axel}

@item --wget
Download using @emph{Wget}

@item -m [@emph{number}], --max-downloads[=@emph{number}]
Parallel download. You can specify the maximum number of downloads to be made simultaneously

@item --login
Use any registered accounts for the enabled services (configure ZDL)

@item -u, --update
Update ZDL

@item -f, --force
Force manual update of ZDL


@item --clean
Delete any temporary files in the destination directory before downloading

@item -d, --daemon
Start ZDL in @emph{daemon} mode (can be controlled with the interactive interface)

@item -i, --interactive
Launch the interactive ZDL interface for downloads that target the current directory. Managed downloads can be active or recorded in temporary directory files

@item -l, --lite
Start ZDL in standard output mode @emph{lite} (mode commands in @emph{standard output} are valid). It can be configured as the default boot mode.

@item --out=@emph{program}|@emph{file}
Output the names of completed download files, in two alternative ways:

@table @emph
@item program
program that can "open" the downloaded file

@item file
text file in which file names are recorded
@end table

@item --live
It allows to select channels for the download of live broadcasts of some televisions in "live stream"

@item --mp3
@itemx --flac
Convert files (even from video to audio) into @acronym{MP3} or into @acronym{FLAC}: they depend on @emph{FFMpeg/AVConv}
                                
@item --ip
Write the current IP address before performing any other operations

@item --reconnect
Force the modem to reconnect at the end of each download, using a script/command/program (configure ZDL)


@item -r, --resume
Recover or download partially downloaded files. It acts in case of homonymy between files (read the manual). It can be configured as the default behavior

@item --no-complete
Clear temporary files of completed downloads

@item --no-stop
Start without interruption: skip any automatic update (which requires entering the password) or request to enter new links. Keyboard input is still available

@end table

@c @end man
@unnumberedsubsubsec Graphical user interface (GUI):
@c @man{6}
@c @ifman @unnumberedsubsec Graphical user interface (GUI):
@table @option
@item -g, --gui
Start the graphical interface in the current directory or in the directory inserted among the arguments, automatically activating zdl --daemon as "core", if zdl has not yet been activated

@item --path-gui
Before starting zdl, it opens a window for selecting the destination directory, if it is not indicated among the command arguments (useful if "zdl --gui" is started by a desktop icon or a web browser extension, as "External Application Button")

@end table

@c @end man
@unnumberedsubsubsec Sockets and user interfaces:
@c @man{6}
@c @ifman @unnumberedsubsec Sockets and user interfaces:
@table @option
@item -s [@emph{port}], --socket[=@emph{port}]
Start the program by connecting it to a socket. If not indicated, the port is the default one.

@item --web-ui
Web user interface.
Start the program in daemon mode in the current directory or, possibly, in the one passed as an argument, a socket at the default port or, if occupied by another application, at the first free port and the default browser at the user interface address.

@end table

@c @end man
@unnumberedsubsubsec IRC/XDCC:
@c @man{7}
@c @ifman @unnumberedsubsec IRC/XDCC:
@table @option
@item -x, --xdcc
Start the interactive insertion of three data:

@enumerate
@item
the IRC server host (@emph{HOST})

@item
the channel to connect to (@emph{CHAN})

@item
the private message (@emph{PRIVMSG}) containing the command @command{XDCC SEND}
@end enumerate

The download via IRC/XDCC can be done, alternatively and without using options, by entering the information in the link, which must have the following form (port not necessary if it is 6667): @code{irc://[HOST[:PORT]]/[CHAN]/msg [PRIVMSG]}. ZDL also accepts links of @emph{xWeasel}, with protocol @code{xdcc://}

@end table


@c @end man
@unnumberedsubsubsec Torrent:
@c @man{8}
@c @ifman @unnumberedsubsec Torrent:
@table @option
@item -T @emph{file}, --torrent-file=@emph{file}
Torrent file for Aria2: may not have a .torrent extension

@item --tcp-port=@emph{port}
@itemx --udp-port=@emph{port}
Open TCP and UDP ports: check the router settings

@end table

@c @end man
@unnumberedsubsubsec Filters:
@c @man{9}
@c @ifman @unnumberedsubsec Filters:
@table @option
@item --scrape-url=@emph{Web page URL}
Extract URLs (links) from the indicated web page and append them to the registered list

@item --scrape-url
Extract URLs (links) from web pages indicated as @emph{link}

@item --url=@emph{regex}
Process only the URLs (the links) that correspond to the REGEX

@item --no-url=@emph{regex}
It does not process the URLs (links) that correspond to the REGEX

@item --file=@emph{regex}
Download only files whose name corresponds to the REGEX

@item --no-file=@emph{regex}
It does not download files whose name corresponds to REGEX

@item --no-rev
Do not download files with '.rev' extension

@item --no-sub
It does not download files whose name contains the string 'sub' (in upper and lower case), it discards the subtitled video files.

@end table

@c @end man
@unnumberedsubsubsec Starting with an editor:
@c @man{10}
@c @ifman @unnumberedsubsec Starting with an editor:
@table @option
@item -e, --editor
replaces the ZDL input interface with the system default editor or with the one configured for ZDL with @command{zdl -c}
@item --emacs, --emacs-nw
use Emacs or its plain text/non-graphic version
@item --jed
use Jed, a small Emacs-style editor
@item --jupp
use Jupp
@item --mcedit
use the Midnight Commander editor
@item --mg
use Mg, an Emacs-style micro editor
@item --nano
use the Nano editor
@item --vi, --vim
use the Vi or Vim editor
@item --zile
use Zile, a GNU Emacs-style micro editor

@end table

@c @end man
@unnumberedsubsubsec Starting with Proxy:
@c @man{11}
@c @ifman @unnumberedsubsec Starting with proxy:
@table @option

@item --proxy
Start ZDL by activating a proxy automatically (the default proxy type is Transparent)

@item --proxy=t|a|e
Start ZDL by activating a proxy of the user-defined type:

@itemize @w{}
@item
@option{t} = Transparent

@item
@option{a} = Anonymous

@item
@option{e} = Elite
@end itemize

@item --proxy=@emph{IP}:@emph{PORT}
Start ZDL by activating the proxy indicated by the user, for the entire duration of the download (the proxy is automatically replaced only for the links of the enabled services that need a new IP address)

@end table

@c @end man
@unnumberedsubsubsec Configuration:

@c @man{12}
@c @ifman @unnumberedsubsec Configuration:
@table @option

@item -c, --configure
Configuration interface of ZDL, also allows you to save any hosting service accounts

@item --stream [@emph{parameters}] [--noXterm]
To download the stream by incorporating ZDL in new scripts, the generic model of the parameters for the additional components (comply with the order):

@end table
@c @end man

@htmlend

@node Streaming/hosting services,Start ZDL,The ZDL command,Top
@htmlstart

@unnumbered Download from @emph{video streaming} and @emph{file hosting} services

@c @man{13}
@c @ifman @unnumberedsec OVERVIEW
@c @ifman @unnumberedsubsec Services
ZDL is enabled for downloading from any kind of valid link, including the video stream (from Youtube, Nowvideo, Dailymotion ...) by means of browser extensions, and files shared through the following hosting and streaming services, directly from the link (bypassing the web page player):

@table @emph
@cindex streaming
@cindex video
@item @b{Streaming video skipping browser player:}
__STREAMING__
@cindex download
@cindex file hosting
@item @b{File hosting:}
__DOWNLOAD__
@cindex streaming
@cindex live
@item @b{Live stream:}
__LIVESTREAM__
@cindex generated
@cindex captcha
@item @b{Links generated by the web (even after captcha):}
__GENERATED__ and other services
@cindex short links
@item @b{Short links:}
__SHORTLINKS__

@item @b{All downloadable files with the following browser extensions:}
@emph{Flashgot} of @emph{Firefox/Iceweasel/Icecat}, @kbd{M-x zdl} function of @emph{Conkeror} and script @command{zdl-xterm} (@emph{XXXTerm/Xombrero} and others)

@item @b{All files downloadable with the following programs:}
__PROGRAMS__
@end table

@c @end man

@unnumberedsec Other useful information.

For the following hosting services it is recommended to extend the maximum download limit
(add the @option{-m} option to the instructions listed above,
possibly indicating the maximum number of downloads to be made simultaneously
to proceed with the download in parallel, also through
the use of proxies

Many servers do not allow recovery of interrupted downloads and parallel downloading.
For these services ZDL uses Wget.

Some services require the use of RTMPDump (in its absence, but with limitations, of cURL)

The other services are enabled by default for Aria2.

To download from Sharpfile, Depositfiles and other services,
currently it is necessary to use the web browser to solve the
captcha, generate the link and start the download through the browsers adds-on or with the ZDL booted from the terminal.

The @option{--login} option enables automatic login in the event of the
ZDL configuration includes one or more accounts for the use of a
hosting service. In particular, the registration of many accounts
for Easybytez not only allows the download of files up to size
at 600MB, but also allows multiple files to be downloaded in parallel
without the use of proxies (in this case it is also necessary to specify
@option{-m} or @option{--max-downloads=}). To configure the use of accounts: @command{zdl [-c|--configure]}

For each service or link, should Aria2 fail to connect, try using Axel or Wget.

@htmlend

@node Start ZDL,Stop ZDL,Streaming/hosting services,Top
@htmlstart

@unnumbered Startup mode (CLI/TUI)

@c @man{14}
@c @ifman @unnumberedsubsec Start
ZDL can be started in different ways:

@table @emph
@item @b{A) To enter links and start new downloads:}

@enumerate
@item
automatically generating the list of download links:

@itemize @minus
@item
open a terminal and enter the directory that will contain the downloaded files

@item
start ZDL by typing the command followed by any options

@item
copy the links of the files to download and paste them in the terminal (wrap up after each link)

@item
type @kbd{M-x} (@kbd{M}, the @emph{Meta} key, is @kbd{<Alt>}, @kbd{<Ctrl>} or @kbd{<Esc>})

@end itemize

@item
Using one or more files prepared with a text editor (wrapping after each link) and reachable from the destination directory (indicate a valid path):
@itemize @minus
@item
open a terminal and enter the directory that will contain the downloaded files (alternatively, you can indicate to @emph{ZDL} the working directory)

@item
type the command @command{zdl} followed by the names of the files containing the list of links: @command{zdl} @emph{path/file ...}
@end itemize

@item
By indicating directly to ZDL the links to be processed (if valid links were to be declared invalid, try @emph{1}):
@command{zdl} @emph{link ...}

@item
From the web browser, through the use of additional components (@emph{Flashgot} for @emph{Firefox}, the script @command{zdl-xterm}, the command @command{zdl} in the Conkeror mini-buffer, ...), to the purpose of capturing and saving the stream of a video or another file of any type.

@item
In "daemon" mode (also from interactive mode)

@item
Using an editor, with the option @option{-e} or other more specific (for example, @option{--emacs-nw})
@end enumerate

Files, working directory and links can be entered in any order. All input links are saved in the file @file{links.txt}, in the destination directory.

@item @b{B) To manage downloads already started in "non-interactive" and "daemon" mode:}
by starting the interactive mode in two ways:

@enumerate
@item
in console from the download destination directory, using the command @command{zdl -i} or @command{zdl --interactive}

@item
in "non-interactive" (standard) mode, by typing the @kbd{i} key
@end enumerate
@end table


@c @end man
@htmlend

@node Stop ZDL, Check downloads, Start ZDL, Top
@htmlstart

@unnumbered Stop mode

@c @man{15}
@c @ifman @unnumberedsubsec Stop
ZDL can be stopped in different ways:
@itemize
@item
If the downloads are managed by the "non-interactive"/standard mode:

@enumerate
@item
typing @kbd{M-k} (in this case all downloads started by ZDL in the specified destination directory or in the current one will be interrupted)

@item
typing @kbd{M-q} (all downloads already started in the current directory will not be interrupted, but will no longer be managed by ZDL until a new @emph{standard} or @emph{daemon} instance of the program)
@end enumerate

@item
If the downloads are managed by the "daemon" mode:
through the interactive mode @command{zdl -i} started in the directory managed by the daemon, by typing the "Quit" exit key (capitalized, that is, with @kbd{Shift-q}): @kbd{Q} (in this case the downloads started in the directory will not be interrupted, but will not be managed by ZDL unless it is restarted to manage the same downloads)
@end itemize


@c @end man

@htmlend

@node Check the downloads,User manuals,Stop ZDL,Top
@htmlstart
@unnumbered Check downloads: recovery, deletion, shutdown, reboot ...

Downloads can be controlled in different ways depending on the type of operation to be performed.
Starting from the terminal allows the operations listed in the command presentation to be executed: @ref{The ZDL command}. Since ZDL can be closed without interrupting downloads, this control mode can be adopted at any time, once execution has started. @emph{To close without interrupting downloads}:
@itemize @minus
@item
if started in standard mode, type @kbd{M-q} (@kbd{<Alt> + <q>} keys)
@item
from interactive mode, type @kbd{Q} (@kbd{<Shift> + <q>} keys)
@end itemize

Once @emph{closed} (or even @emph{killed} interrupting downloads), ZDL can be restarted using new options.

@unnumberedsubsec An example, starting from a practical problem: add options to downloads started by the browser.
@table @emph
@item Problem:
I want to download files from Easybytez using @emph{Flashgot}, but also I want to use the options @option{--login}, @option{--max-downloads=} and @option{--clean}, which are not
set by default. How can I use these additional features
using the browser (with @emph{Flashgot}), if these can be activated
only from the terminal?

@item Solution:
@itemize @minus
@item
start zdl in a terminal, from the destination directory,
    using all the options I need:
    @command{zdl -m --login --clean}
@item
using @emph{Firefox}, I click with the right mouse button on the links of
    download file and start the download with @emph{Flashgot}: download
    it is not carried out immediately and the links are registered by zdl for
    be processed by another active instance of the program (that one
    in the terminal)
@item
when I finished recording the links, I go back to the terminal and, without
    write anything, type @kbd{M-x}
@end itemize
@end table

@* @*
@unnumberedsubsec Manual control of downloads.
ZDL processes the registered @emph{links}, generating for each a temporary file from which it can extract information about the file to be downloaded and the download in progress, intact or completed. Thanks to this information, it is possible to control the download processes, either automatically by ZDL, or manually by the user.

ZDL downloads can be controlled manually through the interactive mode, which can be activated from the standard one by entering @kbd{M-i} (@kbd{<Alt>+<i>} keys) or from any @emph{Bash} terminal from the same download directory, using the @option{-i|--interactive} option. If there is no start-up instance and automatic management of downloads, from the interactive interface it is possible to start the @emph{daemon} mode, which acts in background as a @emph{server} and is independent of the startup terminal. To manage the downloads and the closing of ZDL in daemon mode, it is still necessary to use an interactive interface, which acts as @emph{client}. @*
The commands are listed in the same interactive interface: it is possible to modify the maximum number of downloads (from @kbd{1} to @kbd{9}, by typing the number keys, or unlimited, by typing the key @kbd{m} or in pause typing @kbd{0}), the type of downloader to use (Axel o Wget, by typing @emph{a} or @emph{w} or @emph{A}), to start the default editor to edit the list of links to be processed (@emph{e} key), to select, with @emph{s}, the downloads in management @emph{to restart them} (ZDL interrupts the current download and processes the next one until the end of the registered list, then restarts from the first and so on) or @emph{to eliminate them} completely. For these last three operations it is possible to select several downloads at a time, indicating the identification numbers separating them with spaces.

@unnumberedsubsec Manual control of downloads still to be processed.
In the absence of temporary files related to @emph{link} not yet processed, it is possible to intervene manually using an @emph{editor} (@ref{Editor}).

@htmlend

@node User manuals,Ways,Check downloads,Top
@htmlstart
@unnumbered User manuals
Documentation currently available:
@itemize @bullet
@item
online hypertext: @url{http://nongnu.org/zdl}
@item
hypertext in @emph{info} format, which can be consulted with the @command{info zdl} command (to improve navigation, we recommend @command{pinfo} or @command{emacs})
@item
UNIX-style manual page: @command{man zdl}
@end itemize

@htmlend



@node Modes,Readline,User manuals,Top
@htmlstart

@unnumbered Modi
ZDL can be used in different ways:

@unnumberedsec Standard output mode (default and @emph {lite}: @option{-l, --lite}).
Two different @emph{standard output modes} are available: the default one, which punctually informs the user of each operation performed, communicating the relevant data of the downloads in progress and the @emph{lite} mode, extremely compact in the representation of the downloads and @emph{silent} with respect to extraction and analysis processes. The second mode can be started with the option @option{-l} (@option{--lite}) or configured as @emph{default} through the configuration interface: @command{zdl [-c|--configure]}. It is particularly suitable for the user who uses ZDL as an alternative browser downloader, for example through the @emph{Flashgot} extension.
@*
The @emph{standard output modes} are equipped with a @ref{Readline} and accept the following commands, expressed in key combinations:

@table @kbd
@item M-i
start @emph{interactive mode}. The standard output of the terminal is transferred to another mode, without however suspending the activities of the previous mode, which proceed silently.
@item M-e
start the default editor (@ref{Editor}). As for the previous command, the activities are not suspended while using an editor to manipulate the list of links to be processed.
@item M-c
clears information (temporary files) of completed downloads.
@item M-q
allows the exit from ZDL without interrupting the downloaders, which continue to record useful data for a ZDL restart: downloads can be controlled through the functions of an @emph{interactive mode} but, in the event of interruptions, they must be processed using @emph{standard output} or @emph{daemon} modes or through @emph{GUI} or @emph{WebUI}.
@item M-k
kills all processes started in the directory, without deleting temporary files.
@end table

@unnumberedsec Interactive mode (@option{-i, --interactive}).
Allows manual control of downloads (@ref{Check downloads}) and other operations, described in the same interface. @emph{It does not process links} and it is only a @emph{client}: to start the download it is necessary to run an instance @emph{server} of ZDL, like @emph{standard output} or @emph{deamon} modes. The latter can be started from the same interactive mode.
@*
This mode of use is the one that provides more information on the @emph{state} of downloads. Its screen is automatically updated every 15 seconds or manually by typing any key.

